import numpy as np


# part 1
# Implement the following functions, which are used to carry out the forward propagation process:


def initialize_parameters(layer_dims):
    """
    :param layer_dims: an array of the dimensions of each layer in the network (layer 0 is the size of the flattened input, layer L is the output softmax) 
    :return: a dictionary containing the initialized W and b parameters of each layer (W1…WL, b1…bL). 
    """

    parameters = [None]
    for layer in range(1, len(layer_dims)):
        W = np.random.rand(layer_dims[layer], layer_dims[layer - 1]) + 0.5  # values 0.5 - 1.5
        b = np.zeros(layer_dims[layer])
        layer_dict = {'W': W, 'b': b}
        parameters.append(layer_dict)
    return parameters


def linear_forward(A, W, B):
    """
    Implement the linear part of a layer's forward propagation.

    :param A: the activations of the previous layer.
    :param W: the weight matrix of the current layer (of shape [size of current layer, size of previous layer]).
    :param B: the bias vector of the current layer (of shape [size of current layer, 1]).
    :return:
     Z – the linear component of the activation function (i.e., the value before applying the non-linear function)
     linear_cache – a dictionary containing A, W, b (stored for making the backpropagation easier to compute) 
    """

    # Z = W * A + B
    Z = np.matmul(W, A) + B
    linear_cache = {'A': A, 'W': W, 'B': B}
    return Z, linear_cache


def softmax(Z):
    """
    :param Z: the linear component of the activation function
    :return: A – the activations of the layer, activation_cache – returns Z, which will be useful for the backpropagation
    """

    # second version to compute softmax
    # exp = np.exp(Z - np.max(Z))
    # A = exp / exp.sum(axis=0)
    exp_scores = np.exp(Z)
    A = exp_scores / np.sum(exp_scores, axis=1, keepdims=True)
    activation_cache = Z
    return A, activation_cache


def relu(Z):
    """
    :param Z: the linear component of the activation function
    :return: A – the activations of the layer, activation_cache – returns Z, which will be useful for the backpropagation
    """

    A = np.maximum(Z, 0)
    activation_cache = Z
    return A, activation_cache


def linear_activation_forward(A_prev, W, B, activation):
    """
    Implement the forward propagation for the LINEAR->ACTIVATION layer.

    :param A_prev: activations of the previous layer.
    :param W: the weights matrix of the current layer.
    :param B: the bias vector of the current layer.
    :param activation: the activation function to be used (a string, either “softmax” or “relu”).
    :return:
    A – the activations of the current layer.
    cache – a joint dictionary containing both linear_cache and activation_cache.
    """

    Z, linear_cache = linear_forward(A_prev, W, B)
    if activation is "softmax":
        A, activation_cache = softmax(Z)
    elif activation is "relu":
        A, activation_cache = relu(Z)
    else:
        raise Exception("activation should be either softmax or relu")
    cache = {'linear_cache': linear_cache, 'activation_cache': activation_cache}
    return A, cache


def L_model_forward(X, parameters, use_batchnorm):
    """
    Implement forward propagation for the [LINEAR->RELU]*(L-1)->LINEAR->SOFTMAX computation.

    :param X: the data, numpy array of shape (input size, number of examples).
    :param parameters: the initialized W and b parameters of each layer.
    :param use_batchnorm: a boolean flag used to determine whether to apply batchnorm after the activation.
    :return:
    AL – the last post-activation value.
    caches – a list of all the cache objects generated by the linear_forward function.
    """

    caches = [None]
    first_layer = 1
    last_layer = len(parameters) - 1

    # first layer
    A, cache = linear_activation_forward(X, parameters[first_layer]['W'], parameters[first_layer]['B'], "relu")
    caches.append(cache)
    if use_batchnorm:
        A = apply_batchnorm(A)
    # hidden layers
    for layer in range(2, last_layer):
        A, cache = linear_activation_forward(A, parameters[layer]['W'], parameters[layer]['B'], "relu")
        caches.append(cache)
        if use_batchnorm:
            A = apply_batchnorm(A)
    # last layer
    AL, cache = linear_activation_forward(A, parameters[last_layer]['W'], parameters[last_layer]['B'], "softmax")
    caches.append(cache)
    return AL, caches


def compute_cost(AL, Y):
    """
    Implement the cost function defined by equation. The requested cost function is categorical cross-entropy loss.

    :param AL: probability vector corresponding to your label predictions, shape (num_of_classes, number of examples).
    :param Y: the labels vector (i.e. the ground truth).
    :return: the cross-entropy cost
    """

    data_loss = 0
    m = len(AL[0])
    for r in range(m):  # For each element in the batch
        for c in range(len(Y[r, :])):  # For each class
            if Y[r, c] != 0:  # Positive classes
                data_loss += -np.log(AL[r, c]) * Y[r, c]  # We sum the loss per class for each element of the batch
    data_loss = -1 / m * data_loss
    return data_loss


def apply_batchnorm(A):
    """
    performs batchnorm on the received activation values of a given layer.

    :param A: the activation values of a given layer.
    :return: the normalized activation values, based on the formula learned in class.
    """

    mean = np.mean(A, axis=0)
    variance = np.mean((A - mean) ** 2, axis=0)
    float_epsilon = np.finfo(float).eps
    NA = (A - mean) * 1.0 / np.sqrt(variance + float_epsilon)
    return NA


# part 2
# Implement the following functions, which are used to carry out the backward propagation process:

def Linear_backward(dZ, cache):
    """
    Implements the linear part of the backward propagation process for a single layer.

    :param dZ: the gradient of the cost with respect to the linear output of the current layer (layer l).
    :param cache: tuple of values (A_prev, W, b) coming from the forward propagation in the current layer.
    :return:
    dA_prev -- Gradient of the cost with respect to the activation (of the previous layer l-1), same shape as A_prev.
    dW -- Gradient of the cost with respect to W (current layer l), same shape as W.
    db -- Gradient of the cost with respect to b (current layer l), same shape as b.
    """

    dA_prev = np.matmul(cache['linear_cache']['W'].transpose(), dZ)
    dW = np.matmul(dZ, cache['linear_cache']['A'].transpose())
    db = dZ
    return dA_prev, dW, db


def linear_activation_backward(dA, cache):
    """
    Implements the backward propagation for the LINEAR->ACTIVATION layer. The function first computes dZ and then applies the linear_backward function.

    :param dA: post activation gradient of the current layer.
    :param cache: contains both the linear cache and the activations cache.
    :return:
    dA_prev – Gradient of the cost with respect to the activation (of the previous layer l-1), same shape as A_prev.
    dW – Gradient of the cost with respect to W (current layer l), same shape as W.
    db – Gradient of the cost with respect to b (current layer l), same shape as b.
    """

    # activation is always relu, softmax activation should be done only once as only the output layers uses it
    dZ = relu_backward(dA, cache['activation_cache'])
    dA_prev, dW, db = Linear_backward(dZ, cache)
    return dA_prev, dW, db


def relu_backward(dA, activation_cache):
    """
    Implements backward propagation for a ReLU unit.

    :param dA: the post-activation gradient.
    :param activation_cache: contains Z (stored during the forward propagation).
    :return: dZ – gradient of the cost with respect to Z.
    """

    Z = activation_cache
    gZ = reluDerivative(Z)
    dZ = np.matmul(dA, gZ)
    return dZ


def reluDerivative(Z):
    """
    Computes the Relu derivative.
    
    :param Z: the linear component of the activation function.
    :return: the Relu derivative.
    """""

    return (Z > 0).astype(int)


def softmax_backward(dA, activation_cache):
    """
    Implements backward propagation for a softmax unit.

    :param dA: the post-activation gradient.
    :param activation_cache: contains Y.
    :return: dZ – gradient of the cost with respect to Z.
    """

    Y = activation_cache
    dZ = dA - Y
    return dZ


def L_model_backward(AL, Y, caches):
    """
    Implement the backward propagation process for the entire network.

    :param AL: the probabilities vector, the output of the forward propagation (L_model_forward).
    :param Y: the true labels vector (the "ground truth" - true classifications).
    :param caches: list of caches containing for each layer: a) the linear cache; b) the activation.
    :return: Grads - a dictionary with the gradients
             grads["dA" + str(l)] = ...
             grads["dW" + str(l)] = ...
             grads["db" + str(l)] = ...
    """

    Grads = {}
    layers_size = len(caches)
    last_layer = layers_size - 1

    # last layer
    dZ = softmax_backward(AL, Y)
    dA_prev, dW, db = Linear_backward(dZ, caches[last_layer])
    update_Grads(Grads, last_layer, dA_prev, dW, db)

    # hidden layers
    for layer in reversed(range(1, last_layer)):
        dA_prev, dW, db = linear_activation_backward(dA_prev, caches[layer])
        update_Grads(Grads, layer, dA_prev, dW, db)

    return Grads


def update_Grads(Grads, layer, dA_prev, dW, db):
    """
    Update the Grads dictionary.
    :param Grads: The dictionary.
    :param layer: Number of the layer to update.
    :param dA_prev: Gradient of the cost with respect to the activation.
    :param dW: Gradient of the cost with respect to W.
    :param db: Gradient of the cost with respect to b.
    """

    Grads["dW" + str(layer)] = dW
    Grads["db" + str(layer)] = db
    Grads["dA" + str(layer - 1)] = dA_prev


def Update_parameters(parameters, grads, learning_rate):
    """
    Updates parameters using gradient descent

    :param parameters: a python dictionary containing the DNN architecture’s parameters.
    :param grads: a python dictionary containing the gradients (generated by L_model_backward).
    :param learning_rate: the learning rate used to update the parameters (the “alpha”).
    :return: parameters – the updated values of the parameters object provided as input.
    """

    for layer in range(1, len(parameters)):
        parameters[layer]["W"] = parameters[layer]["W"] - learning_rate * grads["dW" + str(layer)]
        parameters[layer]["b"] = parameters[layer]["b"] - learning_rate * grads["db" + str(layer)]
    return parameters


# part 3
# In this section you will use the functions you created in the previous sections to train the network and produce predictions.

def L_layer_model(X, Y, layers_dims, learning_rate, num_iterations, batch_size):
    """
    Implements a L-layer neural network. All layers but the last should have the ReLU activation function, and the final layer will apply the softmax activation
    function. The size of the output layer should be equal to the number of labels in the data.
    Please select a batch size that enables your code to run well (i.e. no memory overflows while still running relatively fast).

    :param X: the input data, a numpy array of shape (height*width , number_of_examples).
    :param Y: the “real” labels of the data, a vector of shape (num_of_classes, number of examples).
    :param layers_dims: a list containing the dimensions of each layer, including the input.
    :param learning_rate: the learning rate.
    :param num_iterations: number of iterations.
    :param batch_size: the number of examples in a single training batch.
    :return:
    """

    # initialize
    parameters = initialize_parameters(layers_dims)
    use_batchnorm = False
    costs = None

    # Partition the dataset into batches of a fixed size
    number_of_batchs = int(len(X[0])/batch_size)
    X_batchs = np.array_split(X, number_of_batchs, axis=1)
    Y_batchs = np.array_split(Y, number_of_batchs, axis=1)

    for i in range(0, num_iterations):
        for i in range(0, number_of_batchs):
            X_batch = X_batchs[i]
            Y_batch = Y_batchs[i]

            # L_model_forward
            AL, caches = L_model_forward(X_batch, parameters, use_batchnorm)

            # compute_cost
            costs = compute_cost(AL, Y_batch)

            # L_model_backward
            Grads = L_model_backward(AL, Y_batch, caches)

            # update parameters
            parameters = Update_parameters(parameters, Grads, learning_rate)

    return parameters, costs


def Predict(X, Y, parameters):
    """
    Description:
    The function receives an input data and the true labels and calculates the accuracy of the trained neural network on the data.

    Input:
    X – the input data, a numpy array of shape (height*width, number_of_examples)
    Y – the “real” labels of the data, a vector of shape (num_of_classes, number of examples)
    Parameters – a python dictionary containing the DNN architecture’s parameters 

    Output:
    accuracy – the accuracy measure of the neural net on the provided data (i.e. the percentage of the samples for which the correct label receives the hughest confidence score). Use the softmax function to normalize the output values.
    """
    pass


# Tests
# layer_dims_test = [3, 4, 1]
# d = initialize_parameters(layer_dims_test)
# a = np.array([[1,2], [3,4]])
# a = a.flatten()
# x = np.ones((3,1)) + 0.5
# w = np.ones((4,3)) + 1
# z = np.matmul(w,x)
# AL = np.array([[0, 0], [0, 0], [0, 0]])
# Y = np.array([[1, 0], [0, 1], [0, 0]])
# cost = compute_cost(AL, Y)
# print(cost)
# a = np.random.rand(3,7)
# b = np.hsplit(a,2)
# c = np.array_split(a, 2, axis=1)
# a = np.array([[1,2], [3,4]])
# at = a.transpose()
print("done")
